/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FeeAssignmentType = IDL.Variant({
  'other' : IDL.Null,
  'annualDay' : IDL.Null,
  'puja' : IDL.Null,
});
export const AppUser = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'role' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Batch = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'name' : IDL.Text,
  'daysOfWeek' : IDL.Vec(IDL.Nat),
  'isActive' : IDL.Bool,
  'monthlyFees' : IDL.Nat,
});
export const FeeAssignmentPayment = IDL.Record({
  'studentId' : IDL.Nat,
  'isPaid' : IDL.Bool,
  'paidDate' : IDL.Opt(IDL.Text),
  'assignmentId' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const FeeAssignment = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'feeType' : FeeAssignmentType,
  'description' : IDL.Text,
  'amount' : IDL.Nat,
});
export const FeePayment = IDL.Record({
  'month' : IDL.Opt(IDL.Nat),
  'studentId' : IDL.Nat,
  'date' : IDL.Text,
  'year' : IDL.Opt(IDL.Nat),
  'feeType' : IDL.Text,
  'paymentMode' : IDL.Text,
  'amount' : IDL.Nat,
  'remarks' : IDL.Text,
  'receiptNumber' : IDL.Nat,
});
export const SoloProgramme = IDL.Record({
  'id' : IDL.Nat,
  'endDate' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'scheduleDays' : IDL.Vec(IDL.Nat),
  'scheduleTime' : IDL.Text,
  'startDate' : IDL.Text,
});
export const SoloRegistration = IDL.Record({
  'feeAmount' : IDL.Nat,
  'studentId' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'isPaid' : IDL.Bool,
  'programmeId' : IDL.Nat,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'dateOfBirth' : IDL.Text,
  'admissionFees' : IDL.Nat,
  'name' : IDL.Text,
  'guardianRelationship' : IDL.Text,
  'isActive' : IDL.Bool,
  'guardianPhone' : IDL.Text,
  'gender' : IDL.Text,
  'contactNumber' : IDL.Text,
  'guardianAadhar' : IDL.Text,
  'currentBatchId' : IDL.Opt(IDL.Nat),
  'guardianName' : IDL.Text,
  'studentAadhar' : IDL.Text,
  'dateOfAdmission' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MonthlyEntry = IDL.Record({
  'month' : IDL.Nat,
  'balance' : IDL.Int,
  'paidAmount' : IDL.Nat,
  'dueAmount' : IDL.Nat,
});
export const DueCard = IDL.Record({
  'studentId' : IDL.Nat,
  'monthlyEntries' : IDL.Vec(MonthlyEntry),
  'year' : IDL.Nat,
  'openingBalance' : IDL.Int,
});
export const OpeningBalanceItem = IDL.Record({
  'description' : IDL.Text,
  'amount' : IDL.Int,
});
export const YearChangeoverRecord = IDL.Record({
  'studentId' : IDL.Nat,
  'totalOpeningBalance' : IDL.Int,
  'toYear' : IDL.Nat,
  'breakdownItems' : IDL.Vec(OpeningBalanceItem),
  'fromYear' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignStudentToBatch' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'createAppUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createBatch' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat), IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createFeeAssignment' : IDL.Func(
      [
        IDL.Text,
        FeeAssignmentType,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Nat),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createSoloProgramme' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'createStudent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'deactivateAppUser' : IDL.Func([IDL.Nat], [], []),
  'deleteBatch' : IDL.Func([IDL.Nat], [], []),
  'generateDueCard' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getAllAppUsers' : IDL.Func([], [IDL.Vec(AppUser)], ['query']),
  'getAllBatches' : IDL.Func([], [IDL.Vec(Batch)], ['query']),
  'getAllFeeAssignmentPaymentsForStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FeeAssignmentPayment)],
      ['query'],
    ),
  'getAllFeeAssignments' : IDL.Func([], [IDL.Vec(FeeAssignment)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(FeePayment)], ['query']),
  'getAllSoloProgrammes' : IDL.Func([], [IDL.Vec(SoloProgramme)], ['query']),
  'getAllSoloRegistrations' : IDL.Func(
      [],
      [IDL.Vec(SoloRegistration)],
      ['query'],
    ),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getBatch' : IDL.Func([IDL.Nat], [IDL.Opt(Batch)], ['query']),
  'getBatchesByDay' : IDL.Func([IDL.Nat], [IDL.Vec(Batch)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentYear' : IDL.Func([], [IDL.Nat], ['query']),
  'getDueCard' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(DueCard)], ['query']),
  'getFeeAssignmentPayments' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FeeAssignmentPayment)],
      ['query'],
    ),
  'getNextReceiptNumber' : IDL.Func([], [IDL.Nat], ['query']),
  'getPaymentsForStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FeePayment)],
      ['query'],
    ),
  'getSoloProgramme' : IDL.Func([IDL.Nat], [IDL.Opt(SoloProgramme)], ['query']),
  'getSoloProgrammesByDay' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SoloProgramme)],
      ['query'],
    ),
  'getSoloRegistrationsForStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SoloRegistration)],
      ['query'],
    ),
  'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
  'getStudentsInBatch' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getYearChangeoverRecord' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Opt(YearChangeoverRecord)],
      ['query'],
    ),
  'guestLogin' : IDL.Func([IDL.Text, IDL.Text], [AppUser], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(AppUser)], []),
  'markFeeAssignmentPaymentPaid' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'markSoloComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'markSoloPaid' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'markStudentInactive' : IDL.Func([IDL.Nat], [], []),
  'performYearChangeover' : IDL.Func([IDL.Nat], [], []),
  'recordFeePayment' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'regenerateDueCardFromMonth' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'registerStudentForSolo' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'resetUserPassword' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDefaultUsers' : IDL.Func([], [], []),
  'updateBatch' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateCurrentYear' : IDL.Func([IDL.Nat], [], []),
  'updateStudent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FeeAssignmentType = IDL.Variant({
    'other' : IDL.Null,
    'annualDay' : IDL.Null,
    'puja' : IDL.Null,
  });
  const AppUser = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'role' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Batch = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'name' : IDL.Text,
    'daysOfWeek' : IDL.Vec(IDL.Nat),
    'isActive' : IDL.Bool,
    'monthlyFees' : IDL.Nat,
  });
  const FeeAssignmentPayment = IDL.Record({
    'studentId' : IDL.Nat,
    'isPaid' : IDL.Bool,
    'paidDate' : IDL.Opt(IDL.Text),
    'assignmentId' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const FeeAssignment = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'feeType' : FeeAssignmentType,
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const FeePayment = IDL.Record({
    'month' : IDL.Opt(IDL.Nat),
    'studentId' : IDL.Nat,
    'date' : IDL.Text,
    'year' : IDL.Opt(IDL.Nat),
    'feeType' : IDL.Text,
    'paymentMode' : IDL.Text,
    'amount' : IDL.Nat,
    'remarks' : IDL.Text,
    'receiptNumber' : IDL.Nat,
  });
  const SoloProgramme = IDL.Record({
    'id' : IDL.Nat,
    'endDate' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'scheduleDays' : IDL.Vec(IDL.Nat),
    'scheduleTime' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const SoloRegistration = IDL.Record({
    'feeAmount' : IDL.Nat,
    'studentId' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'isPaid' : IDL.Bool,
    'programmeId' : IDL.Nat,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'dateOfBirth' : IDL.Text,
    'admissionFees' : IDL.Nat,
    'name' : IDL.Text,
    'guardianRelationship' : IDL.Text,
    'isActive' : IDL.Bool,
    'guardianPhone' : IDL.Text,
    'gender' : IDL.Text,
    'contactNumber' : IDL.Text,
    'guardianAadhar' : IDL.Text,
    'currentBatchId' : IDL.Opt(IDL.Nat),
    'guardianName' : IDL.Text,
    'studentAadhar' : IDL.Text,
    'dateOfAdmission' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MonthlyEntry = IDL.Record({
    'month' : IDL.Nat,
    'balance' : IDL.Int,
    'paidAmount' : IDL.Nat,
    'dueAmount' : IDL.Nat,
  });
  const DueCard = IDL.Record({
    'studentId' : IDL.Nat,
    'monthlyEntries' : IDL.Vec(MonthlyEntry),
    'year' : IDL.Nat,
    'openingBalance' : IDL.Int,
  });
  const OpeningBalanceItem = IDL.Record({
    'description' : IDL.Text,
    'amount' : IDL.Int,
  });
  const YearChangeoverRecord = IDL.Record({
    'studentId' : IDL.Nat,
    'totalOpeningBalance' : IDL.Int,
    'toYear' : IDL.Nat,
    'breakdownItems' : IDL.Vec(OpeningBalanceItem),
    'fromYear' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignStudentToBatch' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'createAppUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createBatch' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat), IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createFeeAssignment' : IDL.Func(
        [
          IDL.Text,
          FeeAssignmentType,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Nat),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createSoloProgramme' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'createStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'deactivateAppUser' : IDL.Func([IDL.Nat], [], []),
    'deleteBatch' : IDL.Func([IDL.Nat], [], []),
    'generateDueCard' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getAllAppUsers' : IDL.Func([], [IDL.Vec(AppUser)], ['query']),
    'getAllBatches' : IDL.Func([], [IDL.Vec(Batch)], ['query']),
    'getAllFeeAssignmentPaymentsForStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FeeAssignmentPayment)],
        ['query'],
      ),
    'getAllFeeAssignments' : IDL.Func([], [IDL.Vec(FeeAssignment)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(FeePayment)], ['query']),
    'getAllSoloProgrammes' : IDL.Func([], [IDL.Vec(SoloProgramme)], ['query']),
    'getAllSoloRegistrations' : IDL.Func(
        [],
        [IDL.Vec(SoloRegistration)],
        ['query'],
      ),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getBatch' : IDL.Func([IDL.Nat], [IDL.Opt(Batch)], ['query']),
    'getBatchesByDay' : IDL.Func([IDL.Nat], [IDL.Vec(Batch)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentYear' : IDL.Func([], [IDL.Nat], ['query']),
    'getDueCard' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(DueCard)], ['query']),
    'getFeeAssignmentPayments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FeeAssignmentPayment)],
        ['query'],
      ),
    'getNextReceiptNumber' : IDL.Func([], [IDL.Nat], ['query']),
    'getPaymentsForStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FeePayment)],
        ['query'],
      ),
    'getSoloProgramme' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SoloProgramme)],
        ['query'],
      ),
    'getSoloProgrammesByDay' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SoloProgramme)],
        ['query'],
      ),
    'getSoloRegistrationsForStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SoloRegistration)],
        ['query'],
      ),
    'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
    'getStudentsInBatch' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getYearChangeoverRecord' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Opt(YearChangeoverRecord)],
        ['query'],
      ),
    'guestLogin' : IDL.Func([IDL.Text, IDL.Text], [AppUser], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(AppUser)], []),
    'markFeeAssignmentPaymentPaid' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'markSoloComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'markSoloPaid' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'markStudentInactive' : IDL.Func([IDL.Nat], [], []),
    'performYearChangeover' : IDL.Func([IDL.Nat], [], []),
    'recordFeePayment' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'regenerateDueCardFromMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'registerStudentForSolo' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'resetUserPassword' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDefaultUsers' : IDL.Func([], [], []),
    'updateBatch' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateCurrentYear' : IDL.Func([IDL.Nat], [], []),
    'updateStudent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };