/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SoloProgramme = IDL.Record({
  'id' : IDL.Nat,
  'endDate' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'startDate' : IDL.Text,
});
export const SoloRegistration = IDL.Record({
  'feeAmount' : IDL.Nat,
  'studentId' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'isPaid' : IDL.Bool,
  'programmeId' : IDL.Nat,
});
export const Batch = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'name' : IDL.Text,
  'daysOfWeek' : IDL.Vec(IDL.Nat),
  'isActive' : IDL.Bool,
  'monthlyFees' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MonthlyEntry = IDL.Record({
  'month' : IDL.Nat,
  'balance' : IDL.Int,
  'paidAmount' : IDL.Nat,
  'dueAmount' : IDL.Nat,
});
export const DueCard = IDL.Record({
  'studentId' : IDL.Nat,
  'monthlyEntries' : IDL.Vec(MonthlyEntry),
  'year' : IDL.Nat,
  'openingBalance' : IDL.Int,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'guardianRelationship' : IDL.Text,
  'isActive' : IDL.Bool,
  'guardianPhone' : IDL.Text,
  'gender' : IDL.Text,
  'contactNumber' : IDL.Text,
  'currentBatchId' : IDL.Opt(IDL.Nat),
  'guardianName' : IDL.Text,
  'dateOfAdmission' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignBatch' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBatch' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat), IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createSoloProgramme' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createStudent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteBatch' : IDL.Func([IDL.Nat], [], []),
  'generateDueCard' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Int], [], []),
  'getAllSoloProgrammes' : IDL.Func([], [IDL.Vec(SoloProgramme)], ['query']),
  'getAllSoloRegistrations' : IDL.Func(
      [],
      [IDL.Vec(SoloRegistration)],
      ['query'],
    ),
  'getBatch' : IDL.Func([IDL.Nat], [Batch], ['query']),
  'getBatchesByDay' : IDL.Func([IDL.Nat], [IDL.Vec(Batch)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentYear' : IDL.Func([], [IDL.Nat], ['query']),
  'getDueCard' : IDL.Func([IDL.Nat, IDL.Nat], [DueCard], ['query']),
  'getSoloProgramme' : IDL.Func([IDL.Nat], [SoloProgramme], ['query']),
  'getSoloRegistrationsForStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SoloRegistration)],
      ['query'],
    ),
  'getStudent' : IDL.Func([IDL.Nat], [Student], ['query']),
  'getStudentsInBatch' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markSoloComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'markSoloPaid' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'markStudentInactive' : IDL.Func([IDL.Nat], [], []),
  'recordFeePayment' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'registerStudentForSolo' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBatch' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateCurrentYear' : IDL.Func([IDL.Nat], [], []),
  'updateStudent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SoloProgramme = IDL.Record({
    'id' : IDL.Nat,
    'endDate' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const SoloRegistration = IDL.Record({
    'feeAmount' : IDL.Nat,
    'studentId' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'isPaid' : IDL.Bool,
    'programmeId' : IDL.Nat,
  });
  const Batch = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'name' : IDL.Text,
    'daysOfWeek' : IDL.Vec(IDL.Nat),
    'isActive' : IDL.Bool,
    'monthlyFees' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MonthlyEntry = IDL.Record({
    'month' : IDL.Nat,
    'balance' : IDL.Int,
    'paidAmount' : IDL.Nat,
    'dueAmount' : IDL.Nat,
  });
  const DueCard = IDL.Record({
    'studentId' : IDL.Nat,
    'monthlyEntries' : IDL.Vec(MonthlyEntry),
    'year' : IDL.Nat,
    'openingBalance' : IDL.Int,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'guardianRelationship' : IDL.Text,
    'isActive' : IDL.Bool,
    'guardianPhone' : IDL.Text,
    'gender' : IDL.Text,
    'contactNumber' : IDL.Text,
    'currentBatchId' : IDL.Opt(IDL.Nat),
    'guardianName' : IDL.Text,
    'dateOfAdmission' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignBatch' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBatch' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat), IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createSoloProgramme' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteBatch' : IDL.Func([IDL.Nat], [], []),
    'generateDueCard' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Int], [], []),
    'getAllSoloProgrammes' : IDL.Func([], [IDL.Vec(SoloProgramme)], ['query']),
    'getAllSoloRegistrations' : IDL.Func(
        [],
        [IDL.Vec(SoloRegistration)],
        ['query'],
      ),
    'getBatch' : IDL.Func([IDL.Nat], [Batch], ['query']),
    'getBatchesByDay' : IDL.Func([IDL.Nat], [IDL.Vec(Batch)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentYear' : IDL.Func([], [IDL.Nat], ['query']),
    'getDueCard' : IDL.Func([IDL.Nat, IDL.Nat], [DueCard], ['query']),
    'getSoloProgramme' : IDL.Func([IDL.Nat], [SoloProgramme], ['query']),
    'getSoloRegistrationsForStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SoloRegistration)],
        ['query'],
      ),
    'getStudent' : IDL.Func([IDL.Nat], [Student], ['query']),
    'getStudentsInBatch' : IDL.Func([IDL.Nat], [IDL.Vec(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markSoloComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'markSoloPaid' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'markStudentInactive' : IDL.Func([IDL.Nat], [], []),
    'recordFeePayment' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'registerStudentForSolo' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBatch' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateCurrentYear' : IDL.Func([IDL.Nat], [], []),
    'updateStudent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };