/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppUser {
  'id' : bigint,
  'username' : string,
  'password' : string,
  'role' : string,
  'mobileNumber' : string,
  'isActive' : boolean,
}
export interface AttendanceRecord {
  'id' : bigint,
  'status' : AttendanceStatus,
  'studentId' : bigint,
  'date' : string,
  'submittedBy' : string,
  'isLocked' : boolean,
  'batchId' : bigint,
}
export type AttendanceStatus = { 'present' : null } |
  { 'absent' : null } |
  { 'holiday' : null };
export interface Batch {
  'id' : bigint,
  'startTime' : string,
  'endTime' : string,
  'name' : string,
  'daysOfWeek' : Array<bigint>,
  'isActive' : boolean,
  'monthlyFees' : bigint,
}
export interface DueCard {
  'studentId' : bigint,
  'monthlyEntries' : Array<MonthlyEntry>,
  'year' : bigint,
  'openingBalance' : bigint,
}
export interface FeeAssignment {
  'id' : bigint,
  'name' : string,
  'year' : bigint,
  'feeType' : FeeAssignmentType,
  'description' : string,
  'amount' : bigint,
}
export interface FeeAssignmentPayment {
  'studentId' : bigint,
  'isPaid' : boolean,
  'paidDate' : [] | [string],
  'assignmentId' : bigint,
  'amount' : bigint,
}
export type FeeAssignmentType = { 'other' : null } |
  { 'annualDay' : null } |
  { 'puja' : null };
export interface FeePayment {
  'month' : [] | [bigint],
  'studentId' : bigint,
  'date' : string,
  'year' : [] | [bigint],
  'feeType' : string,
  'paymentMode' : string,
  'amount' : bigint,
  'remarks' : string,
  'receiptNumber' : bigint,
}
export interface MonthlyEntry {
  'month' : bigint,
  'balance' : bigint,
  'paidAmount' : bigint,
  'dueAmount' : bigint,
}
export interface OpeningBalanceItem {
  'description' : string,
  'amount' : bigint,
}
export interface SoloProgramme {
  'id' : bigint,
  'endDate' : string,
  'name' : string,
  'description' : string,
  'scheduleDays' : Array<bigint>,
  'scheduleTime' : string,
  'startDate' : string,
}
export interface SoloRegistration {
  'feeAmount' : bigint,
  'studentId' : bigint,
  'isCompleted' : boolean,
  'isPaid' : boolean,
  'programmeId' : bigint,
}
export interface Student {
  'id' : bigint,
  'age' : bigint,
  'dateOfBirth' : string,
  'admissionFees' : bigint,
  'name' : string,
  'motherName' : string,
  'isActive' : boolean,
  'fatherName' : string,
  'gender' : string,
  'contactNumber' : string,
  'motherMobile' : string,
  'guardianAadhar' : string,
  'currentBatchId' : [] | [bigint],
  'studentAadhar' : string,
  'fatherMobile' : string,
  'dateOfAdmission' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface YearChangeoverRecord {
  'studentId' : bigint,
  'totalOpeningBalance' : bigint,
  'toYear' : bigint,
  'breakdownItems' : Array<OpeningBalanceItem>,
  'fromYear' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignStudentToBatch' : ActorMethod<[bigint, bigint, string], undefined>,
  'createAppUser' : ActorMethod<[string, string, string, string], bigint>,
  'createBatch' : ActorMethod<
    [string, Array<bigint>, string, string, bigint],
    bigint
  >,
  'createFeeAssignment' : ActorMethod<
    [string, FeeAssignmentType, bigint, bigint, Array<bigint>, string],
    bigint
  >,
  'createSoloProgramme' : ActorMethod<
    [string, string, string, string, string, Array<bigint>],
    bigint
  >,
  'createStudent' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
    ],
    bigint
  >,
  'deactivateAppUser' : ActorMethod<[bigint], undefined>,
  'deleteBatch' : ActorMethod<[bigint], undefined>,
  'generateDueCard' : ActorMethod<[bigint, bigint], undefined>,
  'getAllAppUsers' : ActorMethod<[], Array<AppUser>>,
  'getAllBatches' : ActorMethod<[], Array<Batch>>,
  'getAllFeeAssignmentPaymentsForStudent' : ActorMethod<
    [bigint],
    Array<FeeAssignmentPayment>
  >,
  'getAllFeeAssignments' : ActorMethod<[], Array<FeeAssignment>>,
  'getAllPayments' : ActorMethod<[], Array<FeePayment>>,
  'getAllSoloProgrammes' : ActorMethod<[], Array<SoloProgramme>>,
  'getAllSoloRegistrations' : ActorMethod<[], Array<SoloRegistration>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAttendanceForBatch' : ActorMethod<
    [bigint, string],
    Array<AttendanceRecord>
  >,
  'getAttendanceForStudent' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'getBatch' : ActorMethod<[bigint], [] | [Batch]>,
  'getBatchesByDay' : ActorMethod<[bigint], Array<Batch>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  /**
   * / Copied types from original actor
   */
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentYear' : ActorMethod<[], bigint>,
  'getDueCard' : ActorMethod<[bigint, bigint], [] | [DueCard]>,
  'getFeeAssignmentPayments' : ActorMethod<
    [bigint],
    Array<FeeAssignmentPayment>
  >,
  'getNextReceiptNumber' : ActorMethod<[], bigint>,
  'getPaymentsForStudent' : ActorMethod<[bigint], Array<FeePayment>>,
  'getSoloProgramme' : ActorMethod<[bigint], [] | [SoloProgramme]>,
  'getSoloProgrammesByDay' : ActorMethod<[bigint], Array<SoloProgramme>>,
  'getSoloRegistrationsForStudent' : ActorMethod<
    [bigint],
    Array<SoloRegistration>
  >,
  'getStudent' : ActorMethod<[bigint], [] | [Student]>,
  'getStudentsInBatch' : ActorMethod<[bigint], Array<Student>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getYearChangeoverRecord' : ActorMethod<
    [bigint, bigint],
    [] | [YearChangeoverRecord]
  >,
  'guestLogin' : ActorMethod<[string, string], AppUser>,
  'isAttendanceSubmitted' : ActorMethod<[bigint, string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginUser' : ActorMethod<[string, string], [] | [AppUser]>,
  'markFeeAssignmentPaymentPaid' : ActorMethod<
    [bigint, bigint, string],
    undefined
  >,
  'markHoliday' : ActorMethod<[bigint, string, string], undefined>,
  'markSoloComplete' : ActorMethod<[bigint, bigint], undefined>,
  'markSoloPaid' : ActorMethod<[bigint, bigint], undefined>,
  'markStudentInactive' : ActorMethod<[bigint], undefined>,
  'modifyAttendance' : ActorMethod<
    [bigint, string, Array<bigint>, string],
    undefined
  >,
  'performYearChangeover' : ActorMethod<[bigint], undefined>,
  'reactivateStudent' : ActorMethod<[bigint], undefined>,
  'recordFeePayment' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      string,
      [] | [bigint],
      [] | [bigint],
      string,
    ],
    bigint
  >,
  'regenerateDueCardFromMonth' : ActorMethod<
    [bigint, bigint, bigint],
    undefined
  >,
  'registerStudentForSolo' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'resetAllData' : ActorMethod<[], undefined>,
  'resetUserPassword' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDefaultUsers' : ActorMethod<[], undefined>,
  'submitAttendance' : ActorMethod<
    [bigint, string, Array<bigint>, string],
    bigint
  >,
  'updateBatch' : ActorMethod<
    [bigint, string, Array<bigint>, string, string, bigint],
    undefined
  >,
  'updateCurrentYear' : ActorMethod<[bigint], undefined>,
  'updateStudent' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];