/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Batch {
  'id' : bigint,
  'startTime' : string,
  'endTime' : string,
  'name' : string,
  'daysOfWeek' : Array<bigint>,
  'isActive' : boolean,
  'monthlyFees' : bigint,
}
export interface DueCard {
  'studentId' : bigint,
  'monthlyEntries' : Array<MonthlyEntry>,
  'year' : bigint,
  'openingBalance' : bigint,
}
export interface MonthlyEntry {
  'month' : bigint,
  'balance' : bigint,
  'paidAmount' : bigint,
  'dueAmount' : bigint,
}
export interface SoloProgramme {
  'id' : bigint,
  'endDate' : string,
  'name' : string,
  'description' : string,
  'startDate' : string,
}
export interface SoloRegistration {
  'feeAmount' : bigint,
  'studentId' : bigint,
  'isCompleted' : boolean,
  'isPaid' : boolean,
  'programmeId' : bigint,
}
export interface Student {
  'id' : bigint,
  'age' : bigint,
  'name' : string,
  'guardianRelationship' : string,
  'isActive' : boolean,
  'guardianPhone' : string,
  'gender' : string,
  'contactNumber' : string,
  'currentBatchId' : [] | [bigint],
  'guardianName' : string,
  'dateOfAdmission' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignBatch' : ActorMethod<[bigint, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBatch' : ActorMethod<
    [string, Array<bigint>, string, string, bigint],
    bigint
  >,
  'createSoloProgramme' : ActorMethod<[string, string, string, string], bigint>,
  'createStudent' : ActorMethod<
    [string, string, bigint, string, string, string, string, string],
    bigint
  >,
  'deleteBatch' : ActorMethod<[bigint], undefined>,
  'generateDueCard' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'getAllSoloProgrammes' : ActorMethod<[], Array<SoloProgramme>>,
  'getAllSoloRegistrations' : ActorMethod<[], Array<SoloRegistration>>,
  'getBatch' : ActorMethod<[bigint], Batch>,
  'getBatchesByDay' : ActorMethod<[bigint], Array<Batch>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentYear' : ActorMethod<[], bigint>,
  'getDueCard' : ActorMethod<[bigint, bigint], DueCard>,
  'getSoloProgramme' : ActorMethod<[bigint], SoloProgramme>,
  'getSoloRegistrationsForStudent' : ActorMethod<
    [bigint],
    Array<SoloRegistration>
  >,
  'getStudent' : ActorMethod<[bigint], Student>,
  'getStudentsInBatch' : ActorMethod<[bigint], Array<Student>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markSoloComplete' : ActorMethod<[bigint, bigint], undefined>,
  'markSoloPaid' : ActorMethod<[bigint, bigint], undefined>,
  'markStudentInactive' : ActorMethod<[bigint], undefined>,
  'recordFeePayment' : ActorMethod<
    [bigint, string, string, bigint, string, [] | [bigint], [] | [bigint]],
    undefined
  >,
  'registerStudentForSolo' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBatch' : ActorMethod<
    [bigint, string, Array<bigint>, string, string, bigint],
    undefined
  >,
  'updateCurrentYear' : ActorMethod<[bigint], undefined>,
  'updateStudent' : ActorMethod<
    [bigint, string, string, bigint, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];