/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Student {
    id: bigint;
    age: bigint;
    dateOfBirth: string;
    admissionFees: bigint;
    name: string;
    motherName: string;
    isActive: boolean;
    fatherName: string;
    gender: string;
    contactNumber: string;
    motherMobile: string;
    guardianAadhar: string;
    currentBatchId?: bigint;
    studentAadhar: string;
    fatherMobile: string;
    dateOfAdmission: string;
}
export interface AttendanceRecord {
    id: bigint;
    status: AttendanceStatus;
    studentId: bigint;
    date: string;
    submittedBy: string;
    isLocked: boolean;
    batchId: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface FeeAssignmentPayment {
    studentId: bigint;
    isPaid: boolean;
    paidDate?: string;
    assignmentId: bigint;
    amount: bigint;
}
export interface OpeningBalanceItem {
    description: string;
    amount: bigint;
}
export interface YearChangeoverRecord {
    studentId: bigint;
    totalOpeningBalance: bigint;
    toYear: bigint;
    breakdownItems: Array<OpeningBalanceItem>;
    fromYear: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FeePayment {
    month?: bigint;
    studentId: bigint;
    date: string;
    year?: bigint;
    feeType: string;
    paymentMode: string;
    amount: bigint;
    remarks: string;
    receiptNumber: bigint;
}
export interface SoloProgramme {
    id: bigint;
    endDate: string;
    name: string;
    description: string;
    scheduleDays: Array<bigint>;
    scheduleTime: string;
    startDate: string;
}
export interface MonthlyEntry {
    month: bigint;
    balance: bigint;
    paidAmount: bigint;
    dueAmount: bigint;
}
export interface AppUser {
    id: bigint;
    username: string;
    password: string;
    role: string;
    mobileNumber: string;
    isActive: boolean;
}
export interface Batch {
    id: bigint;
    startTime: string;
    endTime: string;
    name: string;
    daysOfWeek: Array<bigint>;
    isActive: boolean;
    monthlyFees: bigint;
}
export interface SoloRegistration {
    feeAmount: bigint;
    studentId: bigint;
    isCompleted: boolean;
    isPaid: boolean;
    programmeId: bigint;
}
export interface FeeAssignment {
    id: bigint;
    name: string;
    year: bigint;
    feeType: FeeAssignmentType;
    description: string;
    amount: bigint;
}
export interface DueCard {
    studentId: bigint;
    monthlyEntries: Array<MonthlyEntry>;
    year: bigint;
    openingBalance: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
}
export enum AttendanceStatus {
    present = "present",
    absent = "absent",
    holiday = "holiday"
}
export enum FeeAssignmentType {
    other = "other",
    annualDay = "annualDay",
    puja = "puja"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignStudentToBatch(studentId: bigint, batchId: bigint, startDate: string): Promise<void>;
    createAppUser(username: string, mobileNumber: string, password: string, role: string): Promise<bigint>;
    createBatch(name: string, daysOfWeek: Array<bigint>, startTime: string, endTime: string, monthlyFees: bigint): Promise<bigint>;
    createFeeAssignment(name: string, feeType: FeeAssignmentType, amount: bigint, year: bigint, studentIds: Array<bigint>, description: string): Promise<bigint>;
    createSoloProgramme(name: string, description: string, startDate: string, endDate: string, scheduleTime: string, scheduleDays: Array<bigint>): Promise<bigint>;
    createStudent(name: string, dateOfAdmission: string, dateOfBirth: string, age: bigint, gender: string, contactNumber: string, studentAadhar: string, fatherName: string, fatherMobile: string, motherName: string, motherMobile: string, guardianAadhar: string, admissionFees: bigint): Promise<bigint>;
    deactivateAppUser(userId: bigint): Promise<void>;
    deleteBatch(id: bigint): Promise<void>;
    generateDueCard(studentId: bigint, year: bigint): Promise<void>;
    getAllAppUsers(): Promise<Array<AppUser>>;
    getAllBatches(): Promise<Array<Batch>>;
    getAllFeeAssignmentPaymentsForStudent(studentId: bigint): Promise<Array<FeeAssignmentPayment>>;
    getAllFeeAssignments(): Promise<Array<FeeAssignment>>;
    getAllPayments(): Promise<Array<FeePayment>>;
    getAllSoloProgrammes(): Promise<Array<SoloProgramme>>;
    getAllSoloRegistrations(): Promise<Array<SoloRegistration>>;
    getAllStudents(): Promise<Array<Student>>;
    getAttendanceForBatch(batchId: bigint, date: string): Promise<Array<AttendanceRecord>>;
    getAttendanceForStudent(studentId: bigint): Promise<Array<AttendanceRecord>>;
    getBatch(id: bigint): Promise<Batch | null>;
    getBatchesByDay(day: bigint): Promise<Array<Batch>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    /**
     * / Copied types from original actor
     */
    getCallerUserRole(): Promise<UserRole>;
    getCurrentYear(): Promise<bigint>;
    getDueCard(studentId: bigint, year: bigint): Promise<DueCard | null>;
    getFeeAssignmentPayments(assignmentId: bigint): Promise<Array<FeeAssignmentPayment>>;
    getNextReceiptNumber(): Promise<bigint>;
    getPaymentsForStudent(studentId: bigint): Promise<Array<FeePayment>>;
    getSoloProgramme(id: bigint): Promise<SoloProgramme | null>;
    getSoloProgrammesByDay(day: bigint): Promise<Array<SoloProgramme>>;
    getSoloRegistrationsForStudent(studentId: bigint): Promise<Array<SoloRegistration>>;
    getStudent(id: bigint): Promise<Student | null>;
    getStudentsInBatch(batchId: bigint): Promise<Array<Student>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getYearChangeoverRecord(studentId: bigint, year: bigint): Promise<YearChangeoverRecord | null>;
    guestLogin(name: string, mobileNumber: string): Promise<AppUser>;
    isAttendanceSubmitted(batchId: bigint, date: string): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    loginUser(mobileNumber: string, password: string): Promise<AppUser | null>;
    markFeeAssignmentPaymentPaid(assignmentId: bigint, studentId: bigint, paidDate: string): Promise<void>;
    markHoliday(batchId: bigint, date: string, submittedBy: string): Promise<void>;
    markSoloComplete(studentId: bigint, programmeId: bigint): Promise<void>;
    markSoloPaid(studentId: bigint, programmeId: bigint): Promise<void>;
    markStudentInactive(id: bigint): Promise<void>;
    modifyAttendance(batchId: bigint, date: string, presentStudentIds: Array<bigint>, modifiedBy: string): Promise<void>;
    performYearChangeover(toYear: bigint): Promise<void>;
    reactivateStudent(id: bigint): Promise<void>;
    recordFeePayment(studentId: bigint, date: string, feeType: string, amount: bigint, remarks: string, month: bigint | null, year: bigint | null, paymentMode: string): Promise<bigint>;
    regenerateDueCardFromMonth(studentId: bigint, year: bigint, fromMonth: bigint): Promise<void>;
    registerStudentForSolo(studentId: bigint, programmeId: bigint, feeAmount: bigint): Promise<void>;
    resetAllData(): Promise<void>;
    resetUserPassword(userId: bigint, newPassword: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedDefaultUsers(): Promise<void>;
    submitAttendance(batchId: bigint, date: string, presentStudentIds: Array<bigint>, submittedBy: string): Promise<bigint>;
    updateBatch(id: bigint, name: string, daysOfWeek: Array<bigint>, startTime: string, endTime: string, monthlyFees: bigint): Promise<void>;
    updateCurrentYear(year: bigint): Promise<void>;
    updateStudent(id: bigint, name: string, dateOfBirth: string, age: bigint, gender: string, contactNumber: string, studentAadhar: string, fatherName: string, fatherMobile: string, motherName: string, motherMobile: string, guardianAadhar: string): Promise<void>;
}
import type { AppUser as _AppUser, AttendanceRecord as _AttendanceRecord, AttendanceStatus as _AttendanceStatus, Batch as _Batch, DueCard as _DueCard, FeeAssignment as _FeeAssignment, FeeAssignmentPayment as _FeeAssignmentPayment, FeeAssignmentType as _FeeAssignmentType, FeePayment as _FeePayment, SoloProgramme as _SoloProgramme, Student as _Student, UserProfile as _UserProfile, UserRole as _UserRole, YearChangeoverRecord as _YearChangeoverRecord, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignStudentToBatch(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignStudentToBatch(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignStudentToBatch(arg0, arg1, arg2);
            return result;
        }
    }
    async createAppUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppUser(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppUser(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createBatch(arg0: string, arg1: Array<bigint>, arg2: string, arg3: string, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBatch(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBatch(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createFeeAssignment(arg0: string, arg1: FeeAssignmentType, arg2: bigint, arg3: bigint, arg4: Array<bigint>, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createFeeAssignment(arg0, to_candid_FeeAssignmentType_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFeeAssignment(arg0, to_candid_FeeAssignmentType_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createSoloProgramme(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSoloProgramme(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSoloProgramme(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createStudent(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: string, arg12: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            return result;
        }
    }
    async deactivateAppUser(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateAppUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateAppUser(arg0);
            return result;
        }
    }
    async deleteBatch(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBatch(arg0);
            return result;
        }
    }
    async generateDueCard(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.generateDueCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateDueCard(arg0, arg1);
            return result;
        }
    }
    async getAllAppUsers(): Promise<Array<AppUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppUsers();
            return result;
        }
    }
    async getAllBatches(): Promise<Array<Batch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBatches();
            return result;
        }
    }
    async getAllFeeAssignmentPaymentsForStudent(arg0: bigint): Promise<Array<FeeAssignmentPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeeAssignmentPaymentsForStudent(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeeAssignmentPaymentsForStudent(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFeeAssignments(): Promise<Array<FeeAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeeAssignments();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeeAssignments();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPayments(): Promise<Array<FeePayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSoloProgrammes(): Promise<Array<SoloProgramme>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSoloProgrammes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSoloProgrammes();
            return result;
        }
    }
    async getAllSoloRegistrations(): Promise<Array<SoloRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSoloRegistrations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSoloRegistrations();
            return result;
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceForBatch(arg0: bigint, arg1: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceForBatch(arg0, arg1);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceForBatch(arg0, arg1);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAttendanceForStudent(arg0: bigint): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceForStudent(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceForStudent(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBatch(arg0: bigint): Promise<Batch | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatch(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatch(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBatchesByDay(arg0: bigint): Promise<Array<Batch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatchesByDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatchesByDay(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentYear(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentYear();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentYear();
            return result;
        }
    }
    async getDueCard(arg0: bigint, arg1: bigint): Promise<DueCard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDueCard(arg0, arg1);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDueCard(arg0, arg1);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeeAssignmentPayments(arg0: bigint): Promise<Array<FeeAssignmentPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeAssignmentPayments(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeAssignmentPayments(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNextReceiptNumber(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextReceiptNumber();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextReceiptNumber();
            return result;
        }
    }
    async getPaymentsForStudent(arg0: bigint): Promise<Array<FeePayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsForStudent(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsForStudent(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSoloProgramme(arg0: bigint): Promise<SoloProgramme | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSoloProgramme(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSoloProgramme(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSoloProgrammesByDay(arg0: bigint): Promise<Array<SoloProgramme>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSoloProgrammesByDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSoloProgrammesByDay(arg0);
            return result;
        }
    }
    async getSoloRegistrationsForStudent(arg0: bigint): Promise<Array<SoloRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSoloRegistrationsForStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSoloRegistrationsForStudent(arg0);
            return result;
        }
    }
    async getStudent(arg0: bigint): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentsInBatch(arg0: bigint): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsInBatch(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsInBatch(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getYearChangeoverRecord(arg0: bigint, arg1: bigint): Promise<YearChangeoverRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getYearChangeoverRecord(arg0, arg1);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getYearChangeoverRecord(arg0, arg1);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async guestLogin(arg0: string, arg1: string): Promise<AppUser> {
        if (this.processError) {
            try {
                const result = await this.actor.guestLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.guestLogin(arg0, arg1);
            return result;
        }
    }
    async isAttendanceSubmitted(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAttendanceSubmitted(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAttendanceSubmitted(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<AppUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async markFeeAssignmentPaymentPaid(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markFeeAssignmentPaymentPaid(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markFeeAssignmentPaymentPaid(arg0, arg1, arg2);
            return result;
        }
    }
    async markHoliday(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markHoliday(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markHoliday(arg0, arg1, arg2);
            return result;
        }
    }
    async markSoloComplete(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markSoloComplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSoloComplete(arg0, arg1);
            return result;
        }
    }
    async markSoloPaid(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markSoloPaid(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSoloPaid(arg0, arg1);
            return result;
        }
    }
    async markStudentInactive(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markStudentInactive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markStudentInactive(arg0);
            return result;
        }
    }
    async modifyAttendance(arg0: bigint, arg1: string, arg2: Array<bigint>, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.modifyAttendance(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.modifyAttendance(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async performYearChangeover(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.performYearChangeover(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.performYearChangeover(arg0);
            return result;
        }
    }
    async reactivateStudent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reactivateStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reactivateStudent(arg0);
            return result;
        }
    }
    async recordFeePayment(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: bigint | null, arg6: bigint | null, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordFeePayment(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordFeePayment(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n41(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async regenerateDueCardFromMonth(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.regenerateDueCardFromMonth(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.regenerateDueCardFromMonth(arg0, arg1, arg2);
            return result;
        }
    }
    async registerStudentForSolo(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudentForSolo(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudentForSolo(arg0, arg1, arg2);
            return result;
        }
    }
    async resetAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAllData();
            return result;
        }
    }
    async resetUserPassword(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetUserPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetUserPassword(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedDefaultUsers(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDefaultUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDefaultUsers();
            return result;
        }
    }
    async submitAttendance(arg0: bigint, arg1: string, arg2: Array<bigint>, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAttendance(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAttendance(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateBatch(arg0: bigint, arg1: string, arg2: Array<bigint>, arg3: string, arg4: string, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBatch(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBatch(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateCurrentYear(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCurrentYear(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCurrentYear(arg0);
            return result;
        }
    }
    async updateStudent(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            return result;
        }
    }
}
function from_candid_AttendanceRecord_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_FeeAssignmentPayment_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeAssignmentPayment): FeeAssignmentPayment {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_FeeAssignmentType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeAssignmentType): FeeAssignmentType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_FeeAssignment_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeAssignment): FeeAssignment {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_FeePayment_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeePayment): FeePayment {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Batch]): Batch | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DueCard]): DueCard | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SoloProgramme]): SoloProgramme | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_YearChangeoverRecord]): YearChangeoverRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppUser]): AppUser | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: bigint;
    isPaid: boolean;
    paidDate: [] | [string];
    assignmentId: bigint;
    amount: bigint;
}): {
    studentId: bigint;
    isPaid: boolean;
    paidDate?: string;
    assignmentId: bigint;
    amount: bigint;
} {
    return {
        studentId: value.studentId,
        isPaid: value.isPaid,
        paidDate: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.paidDate)),
        assignmentId: value.assignmentId,
        amount: value.amount
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    year: bigint;
    feeType: _FeeAssignmentType;
    description: string;
    amount: bigint;
}): {
    id: bigint;
    name: string;
    year: bigint;
    feeType: FeeAssignmentType;
    description: string;
    amount: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        year: value.year,
        feeType: from_candid_FeeAssignmentType_n19(_uploadFile, _downloadFile, value.feeType),
        description: value.description,
        amount: value.amount
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    month: [] | [bigint];
    studentId: bigint;
    date: string;
    year: [] | [bigint];
    feeType: string;
    paymentMode: string;
    amount: bigint;
    remarks: string;
    receiptNumber: bigint;
}): {
    month?: bigint;
    studentId: bigint;
    date: string;
    year?: bigint;
    feeType: string;
    paymentMode: string;
    amount: bigint;
    remarks: string;
    receiptNumber: bigint;
} {
    return {
        month: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.month)),
        studentId: value.studentId,
        date: value.date,
        year: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.year)),
        feeType: value.feeType,
        paymentMode: value.paymentMode,
        amount: value.amount,
        remarks: value.remarks,
        receiptNumber: value.receiptNumber
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    dateOfBirth: string;
    admissionFees: bigint;
    name: string;
    motherName: string;
    isActive: boolean;
    fatherName: string;
    gender: string;
    contactNumber: string;
    motherMobile: string;
    guardianAadhar: string;
    currentBatchId: [] | [bigint];
    studentAadhar: string;
    fatherMobile: string;
    dateOfAdmission: string;
}): {
    id: bigint;
    age: bigint;
    dateOfBirth: string;
    admissionFees: bigint;
    name: string;
    motherName: string;
    isActive: boolean;
    fatherName: string;
    gender: string;
    contactNumber: string;
    motherMobile: string;
    guardianAadhar: string;
    currentBatchId?: bigint;
    studentAadhar: string;
    fatherMobile: string;
    dateOfAdmission: string;
} {
    return {
        id: value.id,
        age: value.age,
        dateOfBirth: value.dateOfBirth,
        admissionFees: value.admissionFees,
        name: value.name,
        motherName: value.motherName,
        isActive: value.isActive,
        fatherName: value.fatherName,
        gender: value.gender,
        contactNumber: value.contactNumber,
        motherMobile: value.motherMobile,
        guardianAadhar: value.guardianAadhar,
        currentBatchId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.currentBatchId)),
        studentAadhar: value.studentAadhar,
        fatherMobile: value.fatherMobile,
        dateOfAdmission: value.dateOfAdmission
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AttendanceStatus;
    studentId: bigint;
    date: string;
    submittedBy: string;
    isLocked: boolean;
    batchId: bigint;
}): {
    id: bigint;
    status: AttendanceStatus;
    studentId: bigint;
    date: string;
    submittedBy: string;
    isLocked: boolean;
    batchId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n30(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date,
        submittedBy: value.submittedBy,
        isLocked: value.isLocked,
        batchId: value.batchId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    annualDay: null;
} | {
    puja: null;
}): FeeAssignmentType {
    return "other" in value ? FeeAssignmentType.other : "annualDay" in value ? FeeAssignmentType.annualDay : "puja" in value ? FeeAssignmentType.puja : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    absent: null;
} | {
    holiday: null;
}): AttendanceStatus {
    return "present" in value ? AttendanceStatus.present : "absent" in value ? AttendanceStatus.absent : "holiday" in value ? AttendanceStatus.holiday : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeAssignmentPayment>): Array<FeeAssignmentPayment> {
    return value.map((x)=>from_candid_FeeAssignmentPayment_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeeAssignment>): Array<FeeAssignment> {
    return value.map((x)=>from_candid_FeeAssignment_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeePayment>): Array<FeePayment> {
    return value.map((x)=>from_candid_FeePayment_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n28(_uploadFile, _downloadFile, x));
}
function to_candid_FeeAssignmentType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeAssignmentType): _FeeAssignmentType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeeAssignmentType): {
    other: null;
} | {
    annualDay: null;
} | {
    puja: null;
} {
    return value == FeeAssignmentType.other ? {
        other: null
    } : value == FeeAssignmentType.annualDay ? {
        annualDay: null
    } : value == FeeAssignmentType.puja ? {
        puja: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
